import { Montserrat, Poppins } from "next/font/google";
import { languages } from "@/lib/i18n/settings";
import { dir } from "i18next";
import "../globals.css";

const poppins = Poppins({
	subsets: ["latin"],
	weight: ["800", "600", "400"],
	variable: "--font-poppins",
});
const montserrat = Montserrat({
	subsets: ["latin"],
	weight: ["700", "600", "500", "400", "300"],
	variable: "--font-montserrat",
});

export async function generateStaticParams() {
	return languages.map((lng) => ({ lng }));
}

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children, params: { lng } }) {
	return (
		<html lang={lng} dir={dir(lng)}>
			<body
				className={
					montserrat.variable +
					" " +
					poppins.variable +
					" flex min-h-screen w-screen"
				}
			>
				<div className="flex-1 flex flex-col w-full">{children}</div>
			</body>
		</html>
	);
}
